apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-ca-certs
  namespace: infra-monitoring
data:
  ca-certificates.crt: |
    -----BEGIN CERTIFICATE-----
    MIICczCCAfigAwIBAgIUIJ1lyMgnipN5+P92l2fg7/5cRVkwCgYIKoZIzj0EAwMw
    aDELMAkGA1UEBhMCQ1oxDjAMBgNVBAgMBVByYWhhMQ4wDAYDVQQHDAVQcmFoYTEg
    MB4GA1UECgwXQmFua292bmkgaWRlbnRpdGEsIGEucy4xFzAVBgNVBAMMDkJhbmtJ
    RCBSb290IENBMB4XDTIwMTIxMzE1NDQzMloXDTMwMTIxMTE1NDQzMlowaDELMAkG
    A1UEBhMCQ1oxDjAMBgNVBAgMBVByYWhhMQ4wDAYDVQQHDAVQcmFoYTEgMB4GA1UE
    CgwXQmFua292bmkgaWRlbnRpdGEsIGEucy4xFzAVBgNVBAMMDkJhbmtJRCBSb290
    IENBMHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEesldci5Yd8+chECnmpokNa+cH2bS
    q2uTDOMFHeXhbv/gNEqJc+FPJ+BgjDAcxIuj/YdXOhfnwGFfIv8K7vF0F58ZNS+U
    uPNZt0DG637hp4V8Lrtg7xkmZN6MrlWzqAUXo2MwYTAdBgNVHQ4EFgQUKUN4varP
    QTow6HnvJAN68wX+gN8wHwYDVR0jBBgwFoAUKUN4varPQTow6HnvJAN68wX+gN8w
    DwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAYYwCgYIKoZIzj0EAwMDaQAw
    ZgIxAMaRH8Dc8n7WXIDplRlbkX6T27pxXuzmJyo63vo9lQJhX9Ajl0viyj10ETl+
    0bRz0gIxAKry+h8hso2uvWvSExjnbPOvq4+PPd4RKENkGClz9D7XSFjOeeORwBqi
    a7VS6HkK9g==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIICtTCCAjugAwIBAgICEAMwCgYIKoZIzj0EAwMwaDELMAkGA1UEBhMCQ1oxDjAM
    BgNVBAgMBVByYWhhMQ4wDAYDVQQHDAVQcmFoYTEgMB4GA1UECgwXQmFua292bmkg
    aWRlbnRpdGEsIGEucy4xFzAVBgNVBAMMDkJhbmtJRCBSb290IENBMB4XDTIwMTIy
    MzExMDgxMFoXDTI1MTIyMjExMDgxMFowfjELMAkGA1UEBhMCQ1oxDjAMBgNVBAgM
    BVByYWhhMSAwHgYDVQQKDBdCYW5rb3ZuaSBpZGVudGl0YSwgYS5zLjEdMBsGA1UE
    AwwUQmFua0lEIFByb2R1Y3Rpb24gQ0ExHjAcBgkqhkiG9w0BCQEWD2FkbWluQGJh
    bmtpZC5jejB2MBAGByqGSM49AgEGBSuBBAAiA2IABN5Dg3ZwACnrouJ0WOCIESwE
    sgHIMBowhMU5ON5ioX4r2QRO5uIdV/BBg4K8CMJWtvx7wWYqkoitz17sR4XI3dUY
    8nRDN6h427bm+opRmi2VBnGwg+NudLx0XTPJHl0+GaOBoTCBnjAdBgNVHQ4EFgQU
    KqIvck112NG3lIFPM4/0LRMS9+YwHwYDVR0jBBgwFoAUKUN4varPQTow6HnvJAN6
    8wX+gN8wDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAYYwOwYDVR0fBDQw
    MjAwoC6gLIYqaHR0cHM6Ly9jYS5iYW5raWQuY3ovY3JsL3Jvb3Qvcm9vdC5jcmwu
    Y3JsMAoGCCqGSM49BAMDA2gAMGUCMHvhVTnLxCr1z6cIHzOJHCJMrnZfCWNBpy/5
    qGcvcGXyJaZzjPht1mMenMB2neCD9gIxAJBl873EZ07QVpAyYi2RkpELNNGEb4eX
    mg1o+JiqRkDzpzmDXEOgw6vqBxRqNleGUQ==
    -----END CERTIFICATE-----