apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: system-secret-key
  namespace: infra-sentry
spec:
  encryptedData:
    secretkey: AgAsSDbuk1DCS1SoZi4T4K+FoagGyfQsTyulVyQtl7LAGYYE/5fjQIOR1WCN77OQMS1HrWPmojgcaUoikXrahsHykH4GZK+Rhdwf2fv6NUsKp9a1gX4uy8VO9Cy4icxDn4dSc65+eM8HoSrYWSJQukpaUPXQ+ReKlkfp8R+W02meLrstojQ+ZCaU8qjEJGCqrlPqVvaCL3UzVGLjGFy/5J5L36sFQ773UISl97t3H3OAo6dkMfMKZjCtrygPHHCdXaQQ0vc79c0nAudnAch+hZt6ZXcf9n0KVB8NWBmc5nz+Ari3q5ouPGTbWCUOu6fnjJiB3s5wPJv5s3dQxSrgvIccYzVaaZX9BQYLyXUJkcDECxROe+z2KGBfhYJ9M059RQICvAjHtBAYqveRMBytCf++XRdURWAdf9pNPMP3g7lOrMbsBk+QvWixPdSHtl+QkSzCiq8BsCxzwQTv2oPQWzZrITr8ZyBr5GRzlUXDq9dcKZ8Age9R66vL8/uhbGA+yk3CGjcNr4Gzlmn/gMdETZfQIUpKupSznMdD5BQcKsAKr69xk7YCbEIGLNZDPd7Tkbvx7hn4fiTlF+w+WQXyl3umdUtbSb1thqokGaslRdH8NbqxHBRZ9hTyVn5EbVvEJURAZajCb2rDkTXsTSZ0dVSJrQ/mh//88MPEeP3p9BkkPmgc6B/f282V5xBz8Z7edioMGfwT3ON+tpfUwMpbjOnlw7oV5J4t9v4XlDn7Hky+HDuUSUFQxSVNZ9XbUPADjuqhcg==
  template:
    metadata:
      creationTimestamp: null
      name: system-secret-key
      namespace: infra-sentry

