alertmanager:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: bankid-staging-issuer
    hosts:
      - alertmanager.stage.bankid.cz
    tls:
      - secretName: prometheus-am-tls-stage
        hosts:
          - alertmanager.stage.bankid.cz

server:
  retention: "20d"
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: bankid-staging-issuer
    hosts:
      - prometheus.stage.bankid.cz
    tls:
      - secretName: prometheus-tls-stage
        hosts:
          - prometheus.stage.bankid.cz
  resources:
    requests:
      cpu: 250m
      memory: 500Mi
    limits:
      cpu: 500m
      memory: 2Gi

extraScrapeConfigs: |
  - job_name: consul
    metrics_path: "/v1/agent/metrics"
    params:
      format: ["prometheus"]
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names: ["consul"]
    relabel_configs:
      - action: keep
        source_labels: [__address__]
        regex: ".*:8500"
      - separator: ;
        regex: __meta_kubernetes_pod_label_(.+)
        replacement: $1
        action: labelmap
      - source_labels: [__meta_kubernetes_pod_name]
        separator: ;
        regex: (.*)
        target_label: kubernetes_pod_name
        replacement: $1
        action: replace