alertmanager:
  ingress:
    enabled: true
    hosts:
      - alertmanager.tool.bankid.cz
    tls:
      - secretName: prometheus-public-tls-tool
        hosts:
          - alertmanager.tool.bankid.cz

server:
  retention: "20d"
  ingress:
    enabled: true
    hosts:
      - prometheus.tool.bankid.cz
    tls:
      - secretName: prometheus-public-tls-tool
        hosts:
          - prometheus.tool.bankid.cz
  resources:
    requests:
      cpu: 250m
      memory: 500Mi
    limits:
      cpu: 500m
      memory: 2Gi