apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitoring-prometheus
  namespace: infra-monitoring
spec:
  storageClassName: vsphere-retain
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "150Gi"