apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc-rwo
  namespace: infra-monitoring
  labels:
    app: grafana
spec:
  storageClassName: vsphere-retain
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Gi"